"""Protocol the rest of the system uses to talk to iCloud (real or fake)."""

from collections.abc import Iterator
from pathlib import Path
from typing import Protocol

from icloud_archiver.types import CatalogItem


class ICloudPhotos(Protocol):
    def iter_oldest_first(self) -> Iterator[CatalogItem]: ...
    def download_original(self, asset_id: str, dest: Path) -> None: ...
    def download_live_photo(self, asset_id: str, dest: Path) -> None: ...
    def download_edited(self, asset_id: str, dest: Path) -> None: ...
    def delete(self, asset_id: str) -> None: ...
    def empty_trash(self, asset_ids: list[str]) -> None: ...
